version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build --template template.yaml
  post_build:
    commands:
      - sam deploy --template-file .aws-sam/build/template.yaml --stack-name imageProcessor-dev --capabilities CAPABILITY_IAM 
