AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A Lambda function named 'imageProcessor' using an existing role and denying CloudWatch logging.

Resources:
  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: imageProcessor
      Handler: lambda_function.lambda_handler
      Runtime: python3.11  
      CodeUri: . 
      MemorySize: 128
      Timeout: 3
      Role: arn:aws:iam::095031187492:role/service-role/imageProcessor-role-3fedjla9
